return {
    width = 544,
    height = 402,
    shift = util.by_pixel(0, -4),
    line_length = 4,
    lines_per_file = 4,
    filenames = {
        "-1.png",
        "-2.png",
        "-3.png",
        "-4.png",
        "-5.png",
        "-6.png",
        "-7.png",
        "-8.png",
        "-9.png",
        "-10.png",
        "-11.png",
        "-12.png",
        "-13.png",
        "-14.png",
        "-15.png",
        "-16.png",
        "-17.png",
    },
}
